[package]
name = "afk_ignite"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.11.4"
openzeppelin = "1.0.0"
ekubo = { git = "https://github.com/EkuboProtocol/abis", rev = "edb6de8c9baf515f1053bbab3d86825d54a63bc3"}
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[dev-dependencies]
snforge_std = "0.40.0"
assert_macros = "2.11.4"
cairo_test = "2.11.4"